src/Entity/Book.php
<?php

namespace App\Entity;

use App\Repository\BookRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: BookRepository::class)]
#[UniqueEntity(fields: ['isbn'], groups: ['default'], message: 'ISBN already exists.')]
class Book
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(groups: ['default', 'update'])]
    #[Assert\NotNull(groups: ['default', 'update'])]
    #[Assert\Length(min: 3, max: 255, groups: ['default', 'update'])]
    private ?string $title = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotNull(groups: ['default', 'update'])]
    #[Assert\Length(min: 3, max: 255, groups: ['default', 'update'])]
    #[Assert\NotBlank(groups: ['default', 'update'])]
    private ?string $author = null;

    #[ORM\Column]
    #[Assert\NotNull(groups: ['default', 'update'])]
    #[Assert\NotBlank(groups: ['default', 'update'])]
    #[Assert\Range(min:1900, max: 2024, groups: ['default', 'update'])]
    private ?int $release_date = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotNull(groups: ['default', 'update'])]
    #[Assert\NotBlank(groups: ['default', 'update'])]
    #[Assert\Isbn(type: Assert\Isbn::ISBN_10, groups: ['default', 'update'])]
    private ?string $isbn = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getAuthor(): ?string
    {
        return $this->author;
    }

    public function setAuthor(string $author): static
    {
        $this->author = $author;

        return $this;
    }

    public function getReleaseDate(): ?int
    {
        return $this->release_date;
    }

    public function setReleaseDate(int $release_date): static
    {
        $this->release_date = $release_date;

        return $this;
    }

    public function getIsbn(): ?string
    {
        return $this->isbn;
    }

    public function setIsbn(string $isbn): static
    {
        $this->isbn = $isbn;

        return $this;
    }
}

templates/partials/_form.html.twig
<form data-book="{{ mode == "edit" ? book.id : -1 }}" id="create-form" action="#" class="entry-animation-1 mb-0 mt-6 space-y-4 rounded-lg w-[90vw] sm:w-[32rem] p-4 shadow-lg sm:p-6 lg:p-8">
    {% if mode == "edit" %}
        <p class="text-center text-lg font-medium">Update Book</p>
    {% else %}
        <p class="text-center text-lg font-medium">Create A New Book</p>
    {% endif %}

    <div>
        <label for="email" class="sr-only">Title</label>

        <div class="relative">
            <input
                    type="text"
                    name="title"
                    required
                    minlength="3"
                    maxlength="255"
                    class="w-full rounded-lg border-gray-200 p-4 pe-12 text-sm shadow-sm"
                    placeholder="Title"
                    value="{{ mode == "edit" ? book.title : "" }}"
            />

            <span class="absolute inset-y-0 end-0 grid place-content-center px-4"></span>
        </div>
    </div>

    <div>
        <label class="sr-only">Author</label>

        <div class="relative">
            <input
                    type="text"
                    required
                    name="author"
                    minlength="3"
                    maxlength="255"
                    class="w-full rounded-lg border-gray-200 p-4 pe-12 text-sm shadow-sm"
                    placeholder="Author"
                    value="{{ mode == "edit" ? book.author : "" }}"
            />

            <span class="absolute inset-y-0 end-0 grid place-content-center px-4"></span>
        </div>
    </div>

    <div>
        <label class="sr-only">ISBN-10</label>

        <div class="relative">
            <input
                    type="text"
                    required
                    name="isbn"
                    class="w-full rounded-lg border-gray-200 p-4 pe-12 text-sm shadow-sm"
                    placeholder="ISBN-10"
                    value="{{ mode == "edit" ? book.isbn : "" }}"
            />

            <span class="absolute inset-y-0 end-0 grid place-content-center px-4"></span>
        </div>
    </div>

    <div>
        <label for="email" class="sr-only">Release Year</label>

        <div class="relative">
            <input
                    type="number"
                    min="1900"
                    max="{{ year }}"
                    required
                    name="release_date"
                    class="w-full rounded-lg border-gray-200 p-4 pe-12 text-sm shadow-sm"
                    placeholder="Release Year"
                    value="{{ mode == "edit" ? book.releaseDate : year }}"
            />

            <span class="absolute inset-y-0 end-0 grid place-content-center px-4"></span>
        </div>
    </div>

    <button
            type="submit"
            class="block w-full rounded-lg bg-indigo-600 px-5 py-3 text-sm font-medium text-white"
    >
        {% if mode == "edit" %}
            Edit
        {% else %}
            Create
        {% endif %}
    </button>
    <section id="errors"></section>
</form>

templates/partials/_menu_options.html.twig
<li class="w-full rounded-lg px-4 py-2 text-sm font-medium text-gray-500 [text-align:_inherit] hover:bg-gray-100 hover:text-gray-700">
    <a
            href="{{ path("app_books_new") }}"
            class="text-sm font-medium text-gray-700"
    >
        Create New Book
    </a>
</li>

<li>
    <details class="group [&_summary::-webkit-details-marker]:hidden">
        <summary
                class="flex cursor-pointer items-center justify-between rounded-lg px-4 py-2 text-gray-500 hover:bg-gray-100 hover:text-gray-700"
        >
            <span class="text-sm font-medium"> Account </span>

            <span class="shrink-0 transition duration-300 group-open:-rotate-180">
              <svg
                      xmlns="http://www.w3.org/2000/svg"
                      class="size-5"
                      viewBox="0 0 20 20"
                      fill="currentColor"
              >
                <path
                        fill-rule="evenodd"
                        d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z"
                        clip-rule="evenodd"
                />
              </svg>
            </span>
        </summary>

        <ul class="mt-2 space-y-1 px-4">
            <li>
                <button
                        class="login w-full rounded-lg px-4 py-2 text-sm font-medium text-gray-500 [text-align:_inherit] hover:bg-gray-100 hover:text-gray-700"
                >
                    Login
                </button>
            </li>
            <li>
                <button
                        class="register w-full rounded-lg px-4 py-2 text-sm font-medium text-gray-500 [text-align:_inherit] hover:bg-gray-100 hover:text-gray-700"
                >
                    Register
                </button>
            </li>
            <li>
                <button
                        class="logout w-full rounded-lg px-4 py-2 text-sm font-medium text-gray-500 [text-align:_inherit] hover:bg-gray-100 hover:text-gray-700"
                >
                    Logout
                </button>
            </li>
        </ul>
    </details>
</li>

templates/partials/_mobile_nav.html.twig
<ul id="mobile-nav" class="w-full z-10 transition bg-white min-h-64 space-y-1">
    {% include "partials/_menu_options.html.twig" %}
</ul>

templates/partials/_sidebar.html.twig
<div class="flex h-screen flex-col justify-between border-e bg-white">
    <div class="px-4 py-6">
    <div id="logo" class="z-50 grid h-10 cursor-pointer w-32 place-content-center rounded-lg bg-gray-100 text-xs text-gray-600">
      Books App
    </div>
        <ul class="mt-6 space-y-1">
         {% include "partials/_menu_options.html.twig" %}
        </ul>
    </div>

    <div class="sticky inset-x-0 bottom-0 border-t border-gray-100">
        <a href="#" class="flex items-center gap-2 bg-white p-4 hover:bg-gray-50">
            <div>
                <p class="text-xs">
                    <strong class="username block font-medium"></strong>
                </p>
            </div>
        </a>
    </div>
</div>